stages:
- test
- build
- upload
- release

variables:
  DOCKERFILE_PATH: Containerfile
  APP_ANDROID_PLATFORMS: android-arm,android-arm64,android-x64
  PACKAGE_VERSION: "${CI_COMMIT_REF_NAME}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/app-releases"

default:
  tags:
    - dedicated-generic

test-apps:
  stage: test
  image: ghcr.io/cirruslabs/flutter:3.41.4
  script:
    - cd apps
    - cp assets/config.template.json assets/config.json
    - flutter test

test-engine:
  stage: test
  image: ghcr.io/astral-sh/uv:0.10.9-debian-dhi
  script:
    - uv sync --locked
    - uv run pytest

build-android:
  stage: build
  tags:
    - dedicated-build
  rules:
    - if: $CI_COMMIT_TAG
  image: ghcr.io/cirruslabs/flutter:3.41.4
  script:
    - bin/reproducible-build-prepare.sh
    - |
      pushd /tmp/build/org.venkado.relagent/apps
      flutter pub get --enforce-lockfile
      flutter build apk --release --split-per-abi
      flutter build appbundle --release
      popd
    - bin/reproducible-build-collect.sh
  artifacts:
    name: 'android-app'
    paths:
      - apps/build/app/outputs/flutter-apk/*.apk
      - apps/build/app/outputs/bundle/release/*.aab

upload-app-artifacts:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - build-android
  image: curlimages/curl:latest
  script:
    - |
      if [ -f apps/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk ]; then
        curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --fail \
          --upload-file apps/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk \
          "${PACKAGE_REGISTRY_URL}/${PACKAGE_VERSION}/relagent-${PACKAGE_VERSION}-android-arm.apk"
      fi
      if [ -f apps/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ]; then
        curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --fail \
          --upload-file apps/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
          "${PACKAGE_REGISTRY_URL}/${PACKAGE_VERSION}/relagent-${PACKAGE_VERSION}-android-arm64.apk"
      fi
      if [ -f apps/build/app/outputs/flutter-apk/app-x86_64-release.apk ]; then
        curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --fail \
          --upload-file apps/build/app/outputs/flutter-apk/app-x86_64-release.apk \
          "${PACKAGE_REGISTRY_URL}/${PACKAGE_VERSION}/relagent-${PACKAGE_VERSION}-android-x64.apk"
      fi
      if [ -f apps/build/app/outputs/bundle/release/app-release.aab ]; then
        curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --fail \
          --upload-file apps/build/app/outputs/bundle/release/app-release.aab \
          "${PACKAGE_REGISTRY_URL}/${PACKAGE_VERSION}/relagent-${PACKAGE_VERSION}-android.aab"
      fi
      if [ -f apps/build/linux/x64/release/bundle/relagent ]; then
        curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --fail \
          --upload-file apps/build/linux/x64/release/bundle/relagent \
          "${PACKAGE_REGISTRY_URL}/${PACKAGE_VERSION}/relagent-${PACKAGE_VERSION}-linux-x64.bin"
      fi

create-release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - upload-app-artifacts
  image: registry.gitlab.com/gitlab-org/cli:latest
  script:
    - echo "running release job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: |
      Automated release for $CI_COMMIT_TAG

      Please note: Not all download links might be connected to files.
    assets:
      links:
        - name: 'Android arm32 APK'
          direct_asset_path: '/relagent-${PACKAGE_VERSION}-android-arm.apk'
          url: '${PACKAGE_REGISTRY_URL}/${PACKAGE_VERSION}/relagent-${PACKAGE_VERSION}-android-arm.apk'
          link_type: package
        - name: 'Android arm64 APK'
          direct_asset_path: '/relagent-${PACKAGE_VERSION}-android-arm64.apk'
          url: '${PACKAGE_REGISTRY_URL}/${PACKAGE_VERSION}/relagent-${PACKAGE_VERSION}-android-arm64.apk'
          link_type: package
        - name: 'Android x64 APK'
          direct_asset_path: '/relagent-${PACKAGE_VERSION}-android-x64.apk'
          url: '${PACKAGE_REGISTRY_URL}/${PACKAGE_VERSION}/relagent-${PACKAGE_VERSION}-android-x64.apk'
          link_type: package
        - name: 'Android App Bundle'
          direct_asset_path: '/relagent-${PACKAGE_VERSION}-android.aab'
          url: '${PACKAGE_REGISTRY_URL}/${PACKAGE_VERSION}/relagent-${PACKAGE_VERSION}-android.aab'
          link_type: package
