; This file is a template for the settings.ini file.
;
; It is expected at ~/.local/share/org.venkado.relagent-engine/settings.ini
; Some settings can be set using environment variables.

[server]
; IMPORTANT: Please set the secret access key!
; This API-Key protects the api endpoints from unwanted access to your data
; Env var: SERVER_SECRET_ACCESS_KEY
secret_access_key =

; If run as a container, ensure you bind all interfaces using 0.0.0.0
address = 0.0.0.0
; port = 8000
; workers = 1

[provider]
; Configuration for an OpenAI chat compatible endpoint
; Env vars: PROVIDER_API_BASE, PROVIDER_API_KEY, PROVIDER_DEFAULT_MODEL

; LM Studio server on container host
api_base = http://host.containers.internal:1234/v1
api_key =
default_model = openai/gpt-oss-20b

; Ollama server on container host
; api_base = http://host.containers.internal:11434
; api_key =
; default_model = olmo-3:7b-instruct-q8_0

; Lemonade server on container host
; api_base = http://host.containers.internal:3030/api/v1
; api_key =
; default_model = gpt-oss-20b-mxfp4-GGUF

[persistence]
; Storage location for data
data_dir = ~/.local/share/org.venkado.relagent-engine/data

[web]
; Location of the web app build (cd apps && flutter build web --base-href=/app/)

; Containerized web app
source_directory = ./web

; Locally built web app
; source_directory = ./apps/build/web

[instrumentation]
; OpenTelemetry collector endpoint Configuration
; Env var: INSTRUMENTATION_OTLP_ENDPOINT

; service_name = relagent-engine

; Local OpenTelemetry collector
; otlp_endpoint = http://localhost:4318

; Local Arize Phoenix
; otlp_endpoint = http://localhost:6006/v1/traces

; Detailed LLM traces if supported. See: https://opentelemetry.io/docs/specs/semconv/gen-ai/
; gen_ai_collector_enabled = true

[debug]
; raw_data_dump = true
