; This is a minimal settings file for containers.
;
; It is expected at: /app/.local/share/org.venkado.relagent-engine/settings.ini
; inside the container.
; Please mount your own customized settings.ini file to this location in order
; to override default settings.

[server]
address = 0.0.0.0
workers = 1

; IMPORTANT: Please set the secret access key!
; This API-Key protects the api endpoints from unwanted access to your data
; Env var: SERVER_SECRET_ACCESS_KEY
secret_access_key =

[persistence]
data_dir = ~/.local/share/org.venkado.relagent-engine/data

[instrumentation]
; Disable instrumentation to avoid OTLP errors
otlp_endpoint =

[web]
source_directory = ./web
